apiVersion: v1
entries:
  sloop:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2022-11-22T08:33:42.792384+01:00"
    description: Sloop is a kubernetes history visualization tool.
    digest: ae0ba25527d29c679b1d74efa22341b8d23ef637439305e47b19701fa9144b0d
    icon: https://raw.githubusercontent.com/salesforce/sloop/master/other/sloop_logo_color.png
    name: sloop
    urls:
    - sloop-0.1.0.tgz
    version: 0.1.0
generated: "2022-11-22T08:33:42.787619+01:00"
